---

- name: Lab 4.6
  hosts: broken
  connection: local

  environment:
    F5_SERVER: "{{ ansible_host }}"
    F5_USER: "{{ bigip_username }}"
    F5_PASSWORD: "{{ bigip_password }}"
    F5_SERVER_PORT: "{{ bigip_port }}"
    F5_VALIDATE_CERTS: "{{ validate_certs }}"

  tasks:
    - name: Create a pool
      bigip_pool:
        name: lab4.6
        lb_method: round-robin
